parameters:
#    backend.example.class: Vecinos\BackendBundle\Example

services:
#    backend.example:
#        class: %backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
